# Inserts a blank line between shell prompts
add_newline = true

# Replace the "â¯" symbol in the prompt with "âœ"
[character]                            # The name of the module we are configuring is "character"
success_symbol = "[âœ](bold green)"     # The "success_symbol" segment is being set to "âœ" with the color "bold green"

# Wait 10 milliseconds for starship to check files under the current directory.
# scan_timeout = 10

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true
#
format = "$all$directory$character"
# format = "$all"

[directory]
truncation_length = 8
truncation_symbol = "â€¦/"


[dotnet]
format = "[$symbol($version )(ï› $tfm )]($style)"
symbol = "î¿ "
style = "bold italic yellow"

[container]
format = "[$symbol \\[$name\\]]($style) "

[deno]
format = "via [ğŸ¦• $version](green bold) "

[rust]
format = "via [î¨ $version](red bold)"
